workflow:
- publish

shared:
  image: node:6

jobs:
  main:
    environment:
      SD_TEMPLATE_PATH: semantic_release_template.yaml
    steps:
    - install_binaries: npm i -g screwdriver-template-main
    - verify_template: template-validate
  publish:
    steps:
    - install_binaries: npm i -g screwdriver-template-main
    - publish_template: template-publish | tee $SD_ARTIFACTS_DIR/publish.output
    - save_version: cat $SD_ARTIFACTS_DIR/publish.output | awk -F[@\ ] '{print $3}' | tee $SD_ARTIFACTS_DIR/template_version
    - tag_latest: template-tag --name screwdriver-cd/semantic-release --version `cat $SD_ARTIFACTS_DIR/template_version` --tag latest
    - tag_stable: template-tag --name screwdriver-cd/semantic-release --version `cat $SD_ARTIFACTS_DIR/template_version` --tag stable
