shared:
  image: node:18

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
    - install_binaries: npm i -g screwdriver-template-main
    - verify: |
        export SD_TEMPLATE_PATH=semantic_release_template.yaml
        template-validate
  publish-node18:
    requires: [main]
    environment:
      SD_TEMPLATE_PATH: semantic_release_template.yaml
    steps:
    - install_binaries: npm i -g screwdriver-template-main
    - publish_template: template-publish | tee $SD_ARTIFACTS_DIR/publish.output
    - save_version: cat $SD_ARTIFACTS_DIR/publish.output | awk -F[@\ ] '{print $3}' | tee $SD_ARTIFACTS_DIR/template_version
    - tag_latest: template-tag --name screwdriver-cd/semantic-release --version `cat $SD_ARTIFACTS_DIR/template_version` --tag latest
    - tag_stable: template-tag --name screwdriver-cd/semantic-release --version `cat $SD_ARTIFACTS_DIR/template_version` --tag stable
